version: 0.1.1_build'{build}'
os: Windows Server 2012
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
  - cmd: npm install -qg grunt-cli karma-cli bower
  - cmd: npm install
  - cmd: bower install
build_script:
  - grunt build
test_script:
  - grunt test
